services:
    app:
        build:
            context: .
            dockerfile: .docker/php/8.4/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - ${APP_PORT:-80}:80
            - ${VITE_PORT:-5173}:5173
        environment:
            DB_HOST: database
        networks:
            - bridge-network
        extra_hosts:
            host.docker.internal: host-gateway
        tty: true
        depends_on:
            - database
    database:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "database:/var/lib/mysql"
        networks:
            - bridge-network
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=database
        networks:
            - bridge-network
        depends_on:
            - database

volumes:
    database:
        driver: local

networks:
    bridge-network:
        driver: bridge
